/**
 * Database type definitions for the Example App.
 *
 * Generated by: npx supabase gen types typescript --project-id <your-project-id>
 * Re-run this command whenever the database schema changes.
 *
 * Pass this type to client factories for column-level TypeScript safety:
 *   createBrowserApiClient<Database>(apiConfig)
 *   createServerApiClient<Database>(cookieStore, apiConfig)
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      cms_content: {
        Row: {
          id: string
          app_id: string
          key: string
          locale: string
          content_json: Json
          version: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          app_id: string
          key: string
          locale: string
          content_json: Json
          version?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          app_id?: string
          key?: string
          locale?: string
          content_json?: Json
          version?: number | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
